### PR TITLE
Use minimum deployment version for CI

### PR DESCRIPTION
**Pull request by bryankeller**
## Details

Changes the deployment version for CI to 11.0.

## Related Issue

#3 

## Motivation and Context

Our CI should run using the minimum deployment version (11.0 currently) to catch backwards-incompatible additions.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by dfed** [comment]
Reading #3 more closely: do we want to set the minimum deployment target? Or do we want to run CI _on an iOS 11 device_?

**Comment by bryankeller** [comment]
Good question - I suppose the latter is better. And if xcodebuild was already pulling the deployment target from the project file, then this change is basically a NOP.

@dfed do you know how to set that up? Setting the sdk version to 11 causes some errors due to it not being able to find that SDK.

**Comment by dfed** [comment]
I don’t know how to set that up using Github’s workflows. I‘m more familiar with TravisCI‘s functionality. Does github workflow let us select a simulator by OS?

**Comment by bryankeller** [comment]
@dfed I think we're good now! Pretty easy to setup!

**Pull request merged**
